services:
  contentlab-search-backend:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile.backend
    image: contentlab-search-image-backend:latest
    environment:
      - GROVE_API_KEY=${GROVE_API_KEY}
      - GROVE_BASE_URL=${GROVE_BASE_URL}
      - GROVE_CHAT_MODEL=${GROVE_CHAT_MODEL}
      - EMBEDDINGS_URL=${EMBEDDINGS_URL}
      - VOYAGE_API_KEY=${VOYAGE_API_KEY}
      - VOYAGE_EMBEDDING_MODEL=${VOYAGE_EMBEDDING_MODEL}
    ports:
      - "8080:8080"
    restart: always
    container_name: contentlab-search-backend