env:
  NODE_ENV: prod
  
envSecrets:
  MONGODB_URI: contentlab-search
  DATABASE_NAME: contentlab-search
  APP_NAME: contentlab-search
  AWS_REGION: contentlab-search
  NEWS_COLLECTION: contentlab-search
  NEWSAPI_KEY: contentlab-search
  FIRECRAWL_API_KEY: contentlab-search
  REDDIT_COLLECTION: contentlab-search
  SUGGESTION_COLLECTION: contentlab-search
  USER_PROFILES_COLLECTION: contentlab-search
  PREVIEW_COLLECTION: contentlab-search
  REDDIT_CLIENT_ID: contentlab-search
  REDDIT_SECRET: contentlab-search
  REDDIT_USERNAME: contentlab-search
  REDDIT_PASSWORD: contentlab-search
  REDDIT_USER_AGENT: contentlab-search
  TAVILY_API_KEYS: contentlab-search
  NODE_ENV: contentlab-search
  BEDROCK_MODEL_HAIKU: contentlab-search
  BEDROCK_MODEL_COHERE_EMBED: contentlab-search

serviceAccount:
  enabled: true
  irsa:
    accountId: "275662791714"
    roleName: "kanopy-prod-cicd-irsa"