env:
  NODE_ENV: staging
  GROVE_BASE_URL: https://grove-gateway-prod.azure-api.net/grove-foundry-prod/anthropic
  GROVE_CHAT_MODEL: claude-haiku-4-5
  EMBEDDINGS_URL: https://ai.mongodb.com
  VOYAGE_EMBEDDING_MODEL: voyage-4-large

envSecrets:
  MONGODB_URI: contentlab-search
  DATABASE_NAME: contentlab-search
  APP_NAME: contentlab-search
  NEWS_COLLECTION: contentlab-search
  NEWSAPI_KEY: contentlab-search
  REDDIT_COLLECTION: contentlab-search
  SUGGESTION_COLLECTION: contentlab-search
  REDDIT_CLIENT_ID: contentlab-search
  REDDIT_SECRET: contentlab-search
  REDDIT_USER_AGENT: contentlab-search
  TAVILY_API_KEYS: contentlab-search
  GROVE_API_KEY: contentlab-search
  VOYAGE_API_KEY: contentlab-search

serviceAccount:
  enabled: true
  irsa:
    accountId: "275662791714"
    roleName: "kanopy-staging-cicd-irsa"

security:
  dataClassification: "Internal"
  dataDesignation: ["MI"]

ownership:
  driEmail: "benjamin.lorenze@mongodb.com"
