# ---- chat_completions.py ----

# This file is used to generate chat completions using MongoDB's Grove gateway
# (Anthropic Claude models, fronted by Azure APIM).

# Import the necessary libraries.
import logging
import os
from typing import Optional

import httpx
from dotenv import load_dotenv

load_dotenv()

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ---------- Module-level constants ----------

GROVE_BASE_URL = os.getenv(
    "GROVE_BASE_URL",
    "https://grove-gateway-prod.azure-api.net/grove-foundry-prod/anthropic",
)
DEFAULT_GROVE_CHAT_MODEL = os.getenv("GROVE_CHAT_MODEL", "claude-haiku-4-5")
ANTHROPIC_VERSION = "2023-06-01"

# The prompts in llm_output.py ask the model to return a JSON array summarising
# a batch of articles; 512 tokens (the old Bedrock default) truncates that
# response. 4096 gives enough headroom.
DEFAULT_MAX_TOKENS = 4096
DEFAULT_TEMPERATURE = 0.00001

REQUEST_TIMEOUT_SECONDS = 30.0
MAX_RETRIES = 3

# A single module-level httpx.Client, reused across instances. httpx.Client is
# thread-safe, which matters because ContentAnalyzer.analyze_search_results()
# calls predict() concurrently (via ThreadPoolExecutor) for news and Reddit.
_client = httpx.Client(timeout=REQUEST_TIMEOUT_SECONDS)


# ---------- GroveAnthropicChatCompletions Class ----------

class GroveAnthropicChatCompletions:
    """A class to generate chat completions using MongoDB's Grove gateway (Anthropic Claude models)."""
    # Reference: Grove exposes an Anthropic Messages API-shaped endpoint at
    # POST {GROVE_BASE_URL}/v1/messages, fronted by Azure APIM (hence the
    # `api-key` header rather than Anthropic's native `x-api-key`).

    log: logging.Logger = logging.getLogger("GroveAnthropicChatCompletions")

    def __init__(
        self,
        api_key: Optional[str] = None,
        base_url: Optional[str] = None,
        model_id: Optional[str] = None,
    ) -> None:
        """
        Initialize the GroveAnthropicChatCompletions class.

        Args:
            api_key (Optional[str]): The Grove API key. Defaults to the GROVE_API_KEY env var.
            base_url (Optional[str]): The Grove gateway base URL. Defaults to the GROVE_BASE_URL env var.
            model_id (Optional[str]): The model ID to use. Defaults to the GROVE_CHAT_MODEL env var.
        """
        self.api_key = api_key or os.getenv("GROVE_API_KEY")
        self.base_url = base_url or GROVE_BASE_URL
        self.model_id = model_id or DEFAULT_GROVE_CHAT_MODEL

    def predict(self, text: str) -> str:
        """ Predict a chat completion based on the input text.

        Args:
            text (str): The input text to generate a chat completion for.

        Returns:
            str: The chat completion generated by the model.
        """

        headers = {
            # Grove is fronted by Azure APIM, which authenticates with
            # `api-key`, NOT Anthropic's native `x-api-key`.
            "api-key": self.api_key or "",
            "anthropic-version": ANTHROPIC_VERSION,
            "content-type": "application/json",
        }

        # Note: unlike Bedrock's native request shape, there is no
        # `anthropic_version` field in the body - it moves to the header above.
        payload = {
            "model": self.model_id,
            "max_tokens": DEFAULT_MAX_TOKENS,
            "temperature": DEFAULT_TEMPERATURE,
            "messages": [
                {
                    "role": "user",
                    "content": [{"type": "text", "text": text}],
                }
            ],
        }

        url = f"{self.base_url}/v1/messages"

        last_error: Optional[Exception] = None
        for attempt in range(1, MAX_RETRIES + 1):
            try:
                response = _client.post(url, headers=headers, json=payload)
                response.raise_for_status()
                return response.json()["content"][0]["text"]
            except (httpx.HTTPError, KeyError, IndexError) as e:
                last_error = e
                self.log.warning(
                    f"Attempt {attempt}/{MAX_RETRIES} failed calling Grove model '{self.model_id}': {e}"
                )

        # Raise instead of exit(1): a single API hiccup must not kill the
        # uvicorn worker process. Let callers decide how to handle failures.
        self.log.error(f"ERROR: Can't invoke '{self.model_id}'. Reason: {last_error}")
        raise RuntimeError(
            f"Grove chat completion failed for model '{self.model_id}': {last_error}"
        ) from last_error
