# ---- embeddings_client.py ----

# This file is used to generate text embeddings using MongoDB's hosted Voyage
# embeddings endpoint (an OpenAI-compatible /v1/embeddings shape).

# Import the necessary libraries.
import logging
import os
import time
from typing import List, Optional

import httpx
from dotenv import load_dotenv

load_dotenv()

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ---------- Module-level constants ----------

EMBEDDINGS_URL = os.getenv("EMBEDDINGS_URL", "https://ai.mongodb.com")
DEFAULT_VOYAGE_EMBEDDING_MODEL = os.getenv("VOYAGE_EMBEDDING_MODEL", "voyage-4-large")

# Dimension stays 1024, same as the Cohere model it replaces, so Atlas vector
# index definitions do not need to change.
OUTPUT_DIMENSION = 1024

REQUEST_TIMEOUT_SECONDS = 30.0
MAX_RETRIES = 3
RETRY_BACKOFF_SECONDS = 1.0

# A single module-level httpx.Client, reused across instances. httpx.Client is
# thread-safe.
_client = httpx.Client(timeout=REQUEST_TIMEOUT_SECONDS)


# ---------- VoyageEmbeddings Class ----------

class VoyageEmbeddings:
    """A class to generate text embeddings using MongoDB's hosted Voyage embeddings endpoint."""
    # Reference: POST {EMBEDDINGS_URL}/v1/embeddings (OpenAI-compatible request/response shape).

    log: logging.Logger = logging.getLogger("VoyageEmbeddings")

    def __init__(
        self,
        api_key: Optional[str] = None,
        base_url: Optional[str] = None,
        model_id: Optional[str] = None,
    ) -> None:
        """
        Initialize the VoyageEmbeddings class.

        Args:
            api_key (Optional[str]): The Voyage API key. Defaults to the VOYAGE_API_KEY env var.
            base_url (Optional[str]): The embeddings endpoint base URL. Defaults to the EMBEDDINGS_URL env var.
            model_id (Optional[str]): The model ID to use. Defaults to the VOYAGE_EMBEDDING_MODEL env var.
        """
        self.api_key = api_key or os.getenv("VOYAGE_API_KEY")
        self.base_url = (base_url or EMBEDDINGS_URL).rstrip("/")
        self.model_id = model_id or DEFAULT_VOYAGE_EMBEDDING_MODEL

    def predict(self, text: str, input_type: str = "document") -> List[float]:
        """ Predict text embeddings based on the input text.

        Args:
            text (str): The input text to generate embeddings for.
            input_type (str): Either "document" or "query". Voyage embeds queries and
                documents asymmetrically, so this must match how the vector will be used.

        Returns:
            List[float]: The text embeddings generated by the model.
        """

        headers = {"content-type": "application/json"}
        # Omit the Authorization header entirely when the key is empty,
        # rather than sending "Bearer " with a blank token.
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"

        payload = {
            "model": self.model_id,
            "input": [text],
            "input_type": input_type,
            "output_dimension": OUTPUT_DIMENSION,
        }

        url = f"{self.base_url}/v1/embeddings"

        last_error: Optional[Exception] = None
        for attempt in range(1, MAX_RETRIES + 1):
            try:
                response = _client.post(url, headers=headers, json=payload)
                response.raise_for_status()
                return response.json()["data"][0]["embedding"]
            except httpx.HTTPStatusError as e:
                # A 4xx is a bad key or a malformed request; retrying just burns time.
                if e.response.status_code < 500:
                    self.log.error(
                        f"ERROR: Can't invoke '{self.model_id}'. Reason: {e}"
                    )
                    raise RuntimeError(
                        f"Voyage embedding failed for model '{self.model_id}' with status "
                        f"{e.response.status_code}: {e}"
                    ) from e
                last_error = e
                self.log.warning(
                    f"Attempt {attempt}/{MAX_RETRIES} failed calling Voyage model '{self.model_id}': {e}"
                )
            except (httpx.HTTPError, KeyError, IndexError) as e:
                last_error = e
                self.log.warning(
                    f"Attempt {attempt}/{MAX_RETRIES} failed calling Voyage model '{self.model_id}': {e}"
                )

            if attempt < MAX_RETRIES:
                time.sleep(RETRY_BACKOFF_SECONDS * attempt)

        # Raise instead of silently returning None: callers need to know an
        # embedding call failed so they don't write a bad/missing vector.
        self.log.error(f"ERROR: Can't invoke '{self.model_id}'. Reason: {last_error}")
        raise RuntimeError(
            f"Voyage embedding failed for model '{self.model_id}': {last_error}"
        ) from last_error
